import AutoAwesomeRoundedIcon from "@mui/icons-material/AutoAwesomeRounded";

import {
  Avatar,
  List,
  ListItem,
  ListItemAvatar,
  ListItemText,
  Typography,
} from "@mui/material";

import DashboardWidget from "../../../components/ui/DashboardWidget/DashboardWidget";

const recommendations = [
  {
    id: 1,
    title: "Block suspicious IP addresses",
    description:
      "Isolation Forest detected repeated brute-force attempts.",
  },
  {
    id: 2,
    title: "Review PowerShell execution",
    description:
      "Unexpected PowerShell activity observed on multiple hosts.",
  },
  {
    id: 3,
    title: "Enable MFA",
    description:
      "Reduce credential attack risk by enforcing multi-factor authentication.",
  },
];

function AIRecommendation() {
  return (
    <DashboardWidget
      title="AI Recommendations"
      subtitle="Suggested actions generated by AI"
      height={450}
    >
      <List disablePadding>
        {recommendations.map((item) => (
          <ListItem
            key={item.id}
            divider
            disablePadding
            sx={{ py: 2 }}
          >
            <ListItemAvatar>
              <Avatar
                sx={{
                  bgcolor: "#E0F2FE",
                  color: "#0284C7",
                }}
              >
                <AutoAwesomeRoundedIcon />
              </Avatar>
            </ListItemAvatar>

            <ListItemText
              primary={
                <Typography fontWeight={600}>
                  {item.title}
                </Typography>
              }
              secondary={item.description}
            />
          </ListItem>
        ))}
      </List>
    </DashboardWidget>
  );
}

export default AIRecommendation;