import AutoAwesomeRoundedIcon from "@mui/icons-material/AutoAwesomeRounded";

import {
  Avatar,
  List,
  ListItem,
  ListItemAvatar,
  ListItemText,
} from "@mui/material";

import { DashboardWidget } from "../../../components/ui/DashboardWidget";

const insights = [
  {
    id: 1,
    title: "Repeated failed authentication attempts detected.",
  },
  {
    id: 2,
    title: "Possible lateral movement observed.",
  },
  {
    id: 3,
    title: "AI recommends isolating host WS-104.",
  },
];

function AIEventSummary() {
  return (
    <DashboardWidget
      title="AI Event Summary"
      subtitle="Generated by AI correlation engine"
      height={420}
    >
      <List disablePadding>
        {insights.map((item) => (
          <ListItem
            key={item.id}
            divider
            disablePadding
            sx={{ py: 2 }}
          >
            <ListItemAvatar>
              <Avatar
                sx={{
                  bgcolor: "#E0F2FE",
                  color: "#0284C7",
                }}
              >
                <AutoAwesomeRoundedIcon />
              </Avatar>
            </ListItemAvatar>

            <ListItemText primary={item.title} />
          </ListItem>
        ))}
      </List>
    </DashboardWidget>
  );
}

export default AIEventSummary;