import AutoAwesomeRoundedIcon from "@mui/icons-material/AutoAwesomeRounded";

import {
  Avatar,
  Chip,
  List,
  ListItem,
  ListItemAvatar,
  ListItemText,
  Stack,
  Typography,
} from "@mui/material";

import DashboardWidget from "../../../components/ui/DashboardWidget/DashboardWidget";

const insights = [
  {
    id: 1,
    title: "Multiple failed logins detected",
    recommendation:
      "Investigate possible brute-force attack and temporarily block source IPs.",
    confidence: "98%",
  },
  {
    id: 2,
    title: "Anomalous PowerShell execution",
    recommendation:
      "Review endpoint activity and verify execution policy.",
    confidence: "94%",
  },
  {
    id: 3,
    title: "Suspicious outbound traffic",
    recommendation:
      "Inspect firewall logs and isolate affected endpoint if necessary.",
    confidence: "91%",
  },
];

function AIInsights() {
  return (
    <DashboardWidget
      title="AI Recommendations"
      subtitle="Generated by ML detection pipeline"
      height={420}
    >
      <List disablePadding>
        {insights.map((item) => (
          <ListItem
            key={item.id}
            divider
            disablePadding
            sx={{ py: 2 }}
          >
            <ListItemAvatar>
              <Avatar
                sx={{
                  bgcolor: "#E0F2FE",
                  color: "#0284C7",
                }}
              >
                <AutoAwesomeRoundedIcon />
              </Avatar>
            </ListItemAvatar>

            <ListItemText
              primary={
                <Typography fontWeight={600}>
                  {item.title}
                </Typography>
              }
              secondary={
                <Stack spacing={1} mt={1}>
                  <Typography variant="body2">
                    {item.recommendation}
                  </Typography>

                  <Chip
                    size="small"
                    color="primary"
                    label={`Confidence ${item.confidence}`}
                    sx={{ width: "fit-content" }}
                  />
                </Stack>
              }
            />
          </ListItem>
        ))}
      </List>
    </DashboardWidget>
  );
}

export default AIInsights;